[package]
name = "incipisphere_renderer"
version = "0.1.0"
license = "MIT"
authors = ["Lucas Kent <rubickent@gmail.com>"]

[dependencies]
vulkano = { git = "https://github.com/rukai/vulkano", branch = "proc_macro_2_0" }
vulkano-win = { git = "https://github.com/rukai/vulkano", branch = "proc_macro_2_0" }
vulkano-shaders = { git = "https://github.com/rukai/vulkano", branch = "proc_macro_2_0" }
winit = "0.17"
genmesh = "0.6"
nalgebra-glm = "0.1"
winit_input_helper = "0.1"
